name: Update epics
on:
  issues:
    types: [opened, closed, reopened]
jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            require('./epics.js')({context, github, core});
